### ISSUE TITLE
build on ros2-foxy-ubuntu20.04 x86

### ISSUE THREAD

**Issue by cshang412** [ros-tooling/rosbag2_storage_mcap#29]
## Description
colcon build 

### Expected Behavior
support colcon build with no error

### Actual Behavior
```
colcon build
Processing: rosbag2_storage_mcap]                                    
--- stderr: rosbag2_storage_mcap                                      
conanfile.py (mcap/0.0.1): ERROR: Invalid ID: Current cppstd (gnu14) is lower than the required C++ standard (17).. Trying to install dependencies, but this configuration will fail to build a package
/home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:48:36: error: ‘StorageOptions’ in namespace ‘rosbag2_storage’ does not name a type
   48 |   void open(const rosbag2_storage::StorageOptions& storage_options,
      |                                    ^~~~~~~~~~~~~~
/home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:48:8: error: ‘void rosbag2_storage_plugins::MCAPStorage::open(const int&, rosbag2_storage::storage_interfaces::IOFlag)’ marked ‘override’, but does not override
   48 |   void open(const rosbag2_storage::StorageOptions& storage_options,
      |        ^~~~
/home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:128:47: error: ‘StorageOptions’ in namespace ‘rosbag2_storage’ does not name a type
  128 | void MCAPStorage::open(const rosbag2_storage::StorageOptions& storage_options,
      |                                               ^~~~~~~~~~~~~~
/home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp: In member function ‘void rosbag2_storage_plugins::MCAPStorage::open(const int&, rosbag2_storage::storage_interfaces::IOFlag)’:
/home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:132:40: error: request for member ‘uri’ in ‘storage_options’, which is of non-class type ‘const int’
  132 |       relative_path_ = storage_options.uri;
      |                                        ^~~
/home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:148:40: error: request for member ‘uri’ in ‘storage_options’, which is of non-class type ‘const int’
  148 |       relative_path_ = storage_options.uri + FILE_EXTENSION;
      |                                        ^~~
In file included from /opt/ros/foxy/include/class_loader/class_loader_core.hpp:57,
                 from /opt/ros/foxy/include/class_loader/class_loader.hpp:55,
                 from /opt/ros/foxy/include/pluginlib/class_list_macros.hpp:40,
                 from /home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:427:
/opt/ros/foxy/include/class_loader/meta_object.hpp: In instantiation of ‘B* class_loader::impl::MetaObject<C, B>::create() const [with C = rosbag2_storage_plugins::MCAPStorage; B = rosbag2_storage::storage_interfaces::ReadWriteInterface]’:
/opt/ros/foxy/include/class_loader/meta_object.hpp:216:7:   required from here
/opt/ros/foxy/include/class_loader/meta_object.hpp:218:12: error: invalid new-expression of abstract class type ‘rosbag2_storage_plugins::MCAPStorage’
  218 |     return new C;
      |            ^~~~~
/home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:42:7: note:   because the following virtual functions are pure within ‘rosbag2_storage_plugins::MCAPStorage’:
   42 | class MCAPStorage : public rosbag2_storage::storage_interfaces::ReadWriteInterface {
      |       ^~~~~~~~~~~
In file included from /home/david/Documents/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:19:
/opt/ros/foxy/include/rosbag2_storage/storage_interfaces/read_write_interface.hpp:36:8: note: 	‘virtual void rosbag2_storage::storage_interfaces::ReadWriteInterface::open(const string&, rosbag2_storage::storage_interfaces::IOFlag)’
   36 |   void open(const std::string & uri, IOFlag io_flag = IOFlag::READ_WRITE) override = 0;
      |        ^~~~
/opt/ros/foxy/include/rosbag2_storage/storage_interfaces/read_write_interface.hpp:36:8: note: 	‘virtual void rosbag2_storage::storage_interfaces::ReadWriteInterface::open(const string&, rosbag2_storage::storage_interfaces::IOFlag)’
make[2]: *** [CMakeFiles/rosbag2_storage_mcap.dir/build.make:63: CMakeFiles/rosbag2_storage_mcap.dir/src/mcap_storage.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/rosbag2_storage_mcap.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< rosbag2_storage_mcap [34min 19s, exited with code 2]
                                       
Summary: 0 packages finished [34min 19s]
  1 package failed: rosbag2_storage_mcap
  1 package had stderr output: rosbag2_storage_mcap
```

## To Reproduce
** Steps to reproduce the behavior, e.g.
1. git clone repo
2. sudo pip install conan
3. cd repo && colcon build 

## System (please complete the following information)
 - OS: [e.g. Ubuntu Bionic]
 - ROS 2 Distro: [e.g. foxy]

** For ROS 2 bugs - please attach a VCS.repos or Dockerfile if possible to help us reproduce the environment **

**Comment by wep21** [comment]
@jtbandes closed by https://github.com/ros-tooling/rosbag2_storage_mcap/pull/34?
